env:
  - DOCKER_NAME=algorand/conduit

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

# Build mac universal binary.
universal_binaries:
  - replace: true

builds:
  - main: cmd/conduit/main.go
    binary: conduit
    ldflags: >
      -s -w
      -X github.com/algorand/conduit/version.Hash={{.FullCommit}}
      -X github.com/algorand/conduit/version.ShortHash={{.ShortCommit}}
      -X github.com/algorand/conduit/version.CompileTime={{.Timestamp}}
      -X github.com/algorand/conduit/version.ReleaseVersion={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    # skip 386 architecture.
    goarch:
      - amd64
      - arm64

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
    - "{{ .Env.DOCKER_NAME }}:latest{{ if .IsSnapshot }}-snapshot{{ end }}-amd64"
    - "{{ .Env.DOCKER_NAME }}:{{ .Version }}-amd64"
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ .Date }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT
    extra_files:
    - docker/docker-entrypoint.sh
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
    - "{{ .Env.DOCKER_NAME }}:latest{{ if .IsSnapshot }}-snapshot{{ end }}-arm64"
    - "{{ .Env.DOCKER_NAME }}:{{ .Version }}-arm64"
    build_flag_templates:
    - --platform=linux/arm64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ .Date }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT
    extra_files:
    - docker/docker-entrypoint.sh

# automatically select amd64/arm64 when using image.
docker_manifests:
  - name_template: "{{ .Env.DOCKER_NAME }}:{{ .Version }}"
    image_templates:
    - "{{ .Env.DOCKER_NAME }}:{{ .Version }}-amd64"
    - "{{ .Env.DOCKER_NAME }}:{{ .Version }}-arm64"
  - name_template: "{{ .Env.DOCKER_NAME }}:latest{{ if .IsSnapshot }}-snapshot{{ end }}"
    image_templates:
    - "{{ .Env.DOCKER_NAME }}:latest{{ if .IsSnapshot }}-snapshot{{ end }}-amd64"
    - "{{ .Env.DOCKER_NAME }}:latest{{ if .IsSnapshot }}-snapshot{{ end }}-arm64"

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'
