env:
  - DOCKER_GITHUB_NAME=algorand/conduit

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

# Build mac universal binary.
universal_binaries:
  - replace: true

builds:
  - main: cmd/conduit/main.go
    binary: conduit
    ldflags: >
      -s -w
      -X github.com/algorand/conduit/version.Hash={{.FullCommit}}
      -X github.com/algorand/conduit/version.ShortHash={{.ShortCommit}}
      -X github.com/algorand/conduit/version.CompileTime={{.Timestamp}}
      -X github.com/algorand/conduit/version.ReleaseVersion={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    # skip 386 architecture.
    goarch:
      - amd64
      - arm64

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
    - "{{ .Env.DOCKER_GITHUB_NAME }}:latest{{ if .IsSnapshot }}-snapshot{{ end }}-amd64"
    - "{{ .Env.DOCKER_GITHUB_NAME }}:{{ .Version }}-amd64"
    build_flag_templates:
    - --platform=linux/amd64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ .Date }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT
    extra_files:
    - docker/docker-entrypoint.sh
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
    - "{{ .Env.DOCKER_GITHUB_NAME }}:latest{{ if .IsSnapshot }}-snapshot{{ end }}-arm64"
    - "{{ .Env.DOCKER_GITHUB_NAME }}:{{ .Version }}-arm64"
    build_flag_templates:
    - --platform=linux/arm64
    - --label=org.opencontainers.image.title={{ .ProjectName }}
    - --label=org.opencontainers.image.version={{ .Version }}
    - --label=org.opencontainers.image.created={{ .Date }}
    - --label=org.opencontainers.image.revision={{ .FullCommit }}
    - --label=org.opencontainers.image.licenses=MIT
    extra_files:
    - docker/docker-entrypoint.sh

# automatically select amd64/arm64 when using image.
docker_manifests:
  - name_template: "{{ .Env.DOCKER_GITHUB_NAME }}:{{ .Version }}"
    image_templates:
    - "{{ .Env.DOCKER_GITHUB_NAME }}:{{ .Version }}-amd64"
    - "{{ .Env.DOCKER_GITHUB_NAME }}:{{ .Version }}-arm64"
  - name_template: "{{ .Env.DOCKER_GITHUB_NAME }}:latest{{ if .IsSnapshot }}-snapshot{{ end }}"
    image_templates:
    - "{{ .Env.DOCKER_GITHUB_NAME }}:latest{{ if .IsSnapshot }}-snapshot{{ end }}-amd64"
    - "{{ .Env.DOCKER_GITHUB_NAME }}:latest{{ if .IsSnapshot }}-snapshot{{ end }}-arm64"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}_
      {{- .Version }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'

release:
  draft: true
  header: |
    ![GitHub Logo](https://raw.githubusercontent.com/algorand/go-algorand/master/release/release-banner.jpg)
  footer: |
    **Full Changelog**: https://github.com/{{ .Env.DOCKER_GITHUB_NAME }}/compare{{ .PreviousTag }}...{{ .Tag }}
    ---
    [Docker images for this release are available on Docker Hub.](https://hub.docker.com/r/algorand/conduit)
