version: 2.1

orbs:
  go: circleci/go@1.7.0
  codecov: codecov/codecov@3.2.4

parameters:
  ubuntu_image:
    type: string
    default: "ubuntu-2004:202107-02"

workflows:
  version: 2
  build_and_test:
    jobs:
      - test

jobs:
  test:
    machine:
      image: << pipeline.parameters.ubuntu_image >>
    environment:
      CI_E2E_FILENAME: "fa6ad40d/rel-nightly"
    steps:
      - go/install:
          version: "1.17.9"
      - install_dependencies
      - build_conduit
      - install_linter
      - run_tests
      # Change this to run_e2e_tests once we have stable algod binaries containing delta APIs
      - run_e2e_tests_nightly
      - codecov/upload

commands:
  build_conduit:
    description: build project
    steps:
      - checkout
      - run: make

  install_dependencies:
    description: prepare machine for next steps
    steps:
      - checkout

      - run:
          name: Install python and other python dependencies
          command: |
            sudo apt update
            sudo apt -y install python3 python3-pip python3-setuptools python3-wheel libboost-math-dev libffi-dev
            pip3 install e2e_tests/

      - run: echo 'export PATH=$PATH:/usr/local/go/bin:$HOME/.local/bin' >> $BASH_ENV

  install_linter:
    description: Install golangci-lint
    steps:
      - run:
          name: Install golangci-lint
          command: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3

  run_tests:
    steps:
      - run: test -z `go fmt ./...`
      - run: make lint
      - run: make check
      - run:
          command: make test
          no_output_timeout: 15m

  run_e2e_tests:
    steps:
      - run:
          name: Install go-algorand stable binaries
          command: |
            wget https://raw.githubusercontent.com/algorand/go-algorand/rel/stable/cmd/updater/update.sh && chmod 744 update.sh
            ./update.sh -i -c stable -n -d ./ -p /usr/local/go/bin
            export GOPATH=/usr/local/go/
      - run: make e2e-conduit

  run_e2e_tests_nightly:
    steps:
      - run:
          name: Install go-algorand nightly binaries
          command: |
            wget https://raw.githubusercontent.com/algorand/go-algorand/rel/stable/cmd/updater/update.sh && chmod 744 update.sh
            ./update.sh -i -c nightly -n -d ./ -p /usr/local/go/bin
            export GOPATH=/usr/local/go/
      - run: make e2e-conduit
