name: Tests
on:
  pull_request:

env:
    # A stable environment for PRs.
    # Set CHANNEL to nightly and update CI_E2E_FILENAME when adding a new feature.
    # Change back to stable once the new feature is released.
    CI_E2E_FILENAME: "f55ae1c8/rel-nightly"
    CHANNEL: nightly
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install algod
        run: |
            wget https://raw.githubusercontent.com/algorand/go-algorand/rel/stable/cmd/updater/update.sh && chmod 744 update.sh 
            ./update.sh -i -c "$CHANNEL" -n -d ./ -p "$RUNNER_WORKSPACE/algod_bin"
            ls "$RUNNER_WORKSPACE/algod_bin"
            # Make it accessible from runner
            echo "$RUNNER_WORKSPACE/algod_bin" >> $GITHUB_PATH

      - name: Test for algod on path
        run: which algod
      
      - name: Build Conduit
        run: make

      - name: Run tests
        run: make test

      - name: Build e2e tests
        run: pip3 install e2e_tests/

      - name: Run e2e tests
        run: |
          make e2e-conduit

      - name: Upload codecov report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
