name: Tests
on:
  pull_request:
  workflow_dispatch:
    inputs:
      ci_e2e_algod_channel:
        description: 'Release channel for algod installation.'
        default: 'stable'
      ci_e2e_filename:
        description: 'Pattern to use when searching for the CI E2E File.'
        default: 'fa6ad40d/rel-nightly'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Build Conduit
        run: make

      - name: Run tests
        run: make test

      - name: Install algod
        run: |
            INPUT_CHANNEL="${{ github.events.inputs.ci_e2e_algod_channel }}"
            CHANNEL="${INPUT_CHANNEL:stable}"
            echo $CHANNEL
            wget https://raw.githubusercontent.com/algorand/go-algorand/rel/stable/cmd/updater/update.sh && chmod 744 update.sh 
            ./update.sh -i -c "$CHANNEL" -n -d ./ -p /usr/local/go/bin
            export GOPATH=/usr/local/go/

      - name: Build e2e tests
        run: pip3 install e2e_tests/

      - name: Run e2e tests
        run: |
          INPUT_FILENAME="${{ github.events.inputs.ci_e2e_filename }}"
          FILENAME="${INPUT_FILENAME:fa6ad40d/rel-nightly}"
          echo $FILENAME"
          export CI_E2E_FILENAME="${{ github.events.inputs.ci_e2e_filename }}"
          make e2e-conduit

      - name: Upload codecov report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
